# fly.toml

app = 'frequency-monitoring'
primary_region = 'gig'

# A seção [http_service] é a forma moderna de definir seu serviço.
# Ela substitui a seção [[services]] que você estava usando.
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false # <--- Esta linha impede que a máquina durma
  auto_start_machines = true
  min_machines_running = 1   # <--- Garante que pelo menos 1 máquina esteja sempre rodando

  # O Health Check continua aqui para garantir que a app está saudável
  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '30s'
    method = 'GET'
    path = '/actuator/health' # Verifique se seu app Spring Boot expõe este endpoint
