# fly.toml file generated for frequency-monitoring on 2025-08-06T13:30:00-03:00

app = 'frequency-monitoring'
primary_region = 'gig' # Região do Rio de Janeiro (pode ser diferente para você)

[build]
  builder = "paketobuildpacks/builder-jammy-base:latest"

[[services]]
  protocol = 'tcp'
  internal_port = 8080 # Porta padrão do Spring Boot
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  # Health Check usando o Spring Boot Actuator
  [[services.http_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '30s' # Tempo para a aplicação iniciar antes do 1º check
    method = 'GET'
    path = '/actuator/health' # Endpoint do Actuator
    protocol = 'http'
    tls_skip_verify = false