app = 'frequency-monitoring'
primary_region = 'gig'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']
  
  # O Health Check continua aqui para garantir que a app está saudável
  [[services.http_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '30s'
    method = 'GET'
    path = '/actuator/health'
    protocol = 'http'