spring:
  application:
    name: frequencyMonitoring
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    format:
      date: dd/MM/yyyy
  jackson:
    deserialization:
      accept-float-as-int: false
    time-zone: America/Sao_Paulo
    date-format: dd/MM/yyyy
  mapper:
    accept-case-insensitive-enums: true
server:
    address: 0.0.0.0
    port: 8080
